
name: Build innoextract for ARM64 (Android)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y           cmake           git           build-essential           zlib1g-dev           liblzma-dev           libboost-all-dev           gcc-aarch64-linux-gnu           g++-aarch64-linux-gnu

    - name: Configure and Build for ARM64
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release                  -DCMAKE_SYSTEM_NAME=Linux                  -DCMAKE_SYSTEM_PROCESSOR=aarch64                  -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc                  -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++                  -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER                  -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY                  -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
        make -j$(nproc)
        aarch64-linux-gnu-strip innoextract || true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: innoextract-arm64
        path: build/innoextract
